[package]
name = "doug"
version = "0.1.0"
authors = ["Christopher Dignam <chris@dignam.xyz>"]

[dependencies]
clap = "2.26.2"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "*"
colored = "1.5"
