[package]
name = "doug"
description = "A time tracking command-line utility"
repository = "https://github.com/chdsbd/doug"
documentation = "https://github.com/chdsbd/doug/blob/master/README.md"
license = "MIT"
version = "1.1.0"
authors = ["Christopher Dignam <chris@dignam.xyz>"]

[dependencies]
clap = "2.26.2"
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.4"
colored = "1.5"
